### ISSUE TITLE
Cannot build Android

### ISSUE THREAD

**Issue by stief510** [Kerumen/react-native-awesome-card-io#1]
Hi, I am trying to build on Android and it keeps failing with

```
file or directory '.../mobile/node_modules/react-native-awesome-card-io/android/src/release/java', not found
Executing task ':react-native-awesome-card-io:compileReleaseJavaWithJavac' (up-to-date check took 0.012 secs) due to:
  No history is available.
All input files are considered out-of-date for incremental task ':react-native-awesome-card-io:compileReleaseJavaWithJavac'.
Compiling with source level 1.7 and target level 1.7.
:react-native-awesome-card-io:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
file or directory '.../mobile/node_modules/react-native-awesome-card-io/android/src/release/java', not found
Compiling with JDK Java compiler API.
.../mobile/node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:124: error: method does not override or implement a method from a supertype
  @Override
  ^
1 error
:react-native-awesome-card-io:compileReleaseJavaWithJavac FAILED
:react-native-awesome-card-io:compileReleaseJavaWithJavac (Thread[main,5,main]) completed. Took 2.131 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-awesome-card-io:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 27.727 secs
Stopped 0 compiler daemon(s).
```

**Comment by Kerumen** [comment]
Do you have React Native 0.32?

**Comment by stief510** [comment]
I have `0.31`

**Comment by stief510** [comment]
Just saw your edit, thank you.

**Comment by Kerumen** [comment]
I just tried with RN 0.31 and it's working fine. Can you check that the version required in Android Studio is good? Go to a React source file and look in the breadcrumb.

<img width="516" alt="screen shot 2016-08-31 at 00 01 49" src="https://cloud.githubusercontent.com/assets/5436545/18108814/6074ffb6-6f0e-11e6-9422-4438daccf959.png">

**Comment by stief510** [comment]
Well now it works but crashes the app with the following error

```
com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `boolean'
    at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
    at com.cardio.RNCardIOModule.parseConfig(RNCardIOModule.java:61)
    at com.cardio.RNCardIOModule.scanCard(RNCardIOModule.java:43)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:158)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by Kerumen** [comment]
Should be fixed in `v2.0.3`.

**Comment by zevmo** [comment]
@Kerumen Thanks!!!! Looking forward to it on npm

**Comment by Kerumen** [comment]
@zevmo I'm uploading it. I takes a bit thanks to the card.io library..

**Comment by Kerumen** [comment]
@zevmo It's up! ;)

**Comment by zevmo** [comment]
You rock!
